Update second batch of examples to manifest SDK 3.0 ACAPs (#91)

diff --git a/vdo-larod-preprocessing/Dockerfile b/vdo-larod-preprocessing/Dockerfile
--- a/vdo-larod-preprocessing/Dockerfile
+++ b/vdo-larod-preprocessing/Dockerfile
@@ -12,14 +12,24 @@ FROM ${REPO}/${SDK}:${VERSION}-${ARCH}-ubuntu${UBUNTU_VERSION}
 
 # Download model
 WORKDIR /opt/app/model
-RUN curl -o mobilenet_v2_1.0_224_quant.tgz http://download.tensorflow.org/models/tflite_11_05_08/mobilenet_v2_1.0_224_quant.tgz &&\
-	tar -xvf mobilenet_v2_1.0_224_quant.tgz &&\
-	curl -L -o mobilenet_v2_1.0_224_quant_edgetpu.tflite https://github.com/google-coral/edgetpu/raw/master/test_data/mobilenet_v2_1.0_224_quant_edgetpu.tflite &&\
-	curl -L -o imagenet_labels.txt https://github.com/google-coral/edgetpu/raw/master/test_data/imagenet_labels.txt
+RUN curl -o mobilenet_v2_1.0_224_quant.tgz http://download.tensorflow.org/models/tflite_11_05_08/mobilenet_v2_1.0_224_quant.tgz && \
+    tar -xvf mobilenet_v2_1.0_224_quant.tgz && \
+    curl -L -o mobilenet_v2_1.0_224_quant_edgetpu.tflite https://github.com/google-coral/edgetpu/raw/master/test_data/mobilenet_v2_1.0_224_quant_edgetpu.tflite && \
+    curl -L -o imagenet_labels.txt https://github.com/google-coral/edgetpu/raw/master/test_data/imagenet_labels.txt
 
 # Copy the library to application folder
 WORKDIR /opt/app
 COPY ./app .
 
+ARG CHIP=
 # Building the ACAP application
-RUN . /opt/axis/acapsdk/environment-setup* && create-package.sh
+RUN if [ "$CHIP" = cpu ]; then \
+    . /opt/axis/acapsdk/environment-setup* && acap-build . \
+    -a 'model/mobilenet_v2_1.0_224_quant.tflite'; \
+    elif [ "$CHIP" = edgetpu ]; then \
+    . /opt/axis/acapsdk/environment-setup* && acap-build . \
+    -a 'model/mobilenet_v2_1.0_224_quant_edgetpu.tflite'; \
+    else \
+    echo 'Error:' $CHIP 'is not a valid value for the CHIP variable'; \
+    exit 1; \
+    fi
