README: Update introduction links
Update introduction links

diff --git a/.github/workflows/linter-documentation-links.yml b/.github/workflows/linter-documentation-links.yml
--- a/.github/workflows/linter-documentation-links.yml
+++ b/.github/workflows/linter-documentation-links.yml
@@ -20,8 +20,8 @@ jobs:
           workflowfile=linter-documentation-links.yml
 
           # Version specific URL strings
-          acap3_type_urls="help.axis.com/acap-3-developer-guide \
-            www.axis.com/techsup/developer_doc"
+          acap3_base_url="axiscommunications.github.io/acap-documentation/docs/acap-sdk-version-3"
+          acap3_type_urls="$acap3_base_url www.axis.com/techsup/developer_doc"
           acap4_type_urls="axiscommunications.github.io/acap-documentation"
 
           # Decide which SDK version this repo is
@@ -32,25 +32,40 @@ jobs:
             *acap-native-sdk-examples*)
               search_urls=$acap3_type_urls
               incorrect_sdk_version=3
+
+              # Check for incorrect URLs
+              set +e
+              found_error=n
+              for doc_url in $search_urls
+              do
+                found_doc_url=$(grep -nir "$doc_url" --exclude $workflowfile)
+                [ -z "$found_doc_url" ] || {
+                  printf "\nERROR: $doc_url is an ACAP $incorrect_sdk_version documentation URL found in:\n$found_doc_url\n"
+                  found_error=y
+                }
+              done
+              set -e
+
               ;;
             *acap3-examples*)
               search_urls=$acap4_type_urls
               incorrect_sdk_version=4
+
+              # Check for incorrect URLs
+              set +e
+              found_error=n
+              for doc_url in $search_urls
+              do
+                found_doc_url=$(grep -nir "$doc_url" --exclude $workflowfile | grep -v $acap3_base_url)
+                [ -z "$found_doc_url" ] || {
+                  printf "\nERROR: $doc_url is an ACAP $incorrect_sdk_version documentation URL found in:\n$found_doc_url\n"
+                  found_error=y
+                }
+              done
+              set -e
+
               ;;
           esac
-
-          # Check for incorrect URLs
-          set +e
-          found_error=n
-          for doc_url in $search_urls
-          do
-            found_doc_url=$(grep -nir "$doc_url" --exclude $workflowfile)
-            [ -z "$found_doc_url" ] || {
-              printf "\nERROR: $doc_url is an ACAP $incorrect_sdk_version documentation URL found in:\n$found_doc_url\n"
-              found_error=y
-            }
-          done
-          set -e
 
           if [ $found_error = n ]; then
             printf "\nNo ACAP $incorrect_sdk_version documentation URL was found -> PASS"
