Tensorflow-to-larod examples refactoring
Remove build of application and keep model training

diff --git a/.github/workflows/tensorflow-to-larod-artpec8.yml b/.github/workflows/tensorflow-to-larod-artpec8.yml
--- a/.github/workflows/tensorflow-to-larod-artpec8.yml
+++ b/.github/workflows/tensorflow-to-larod-artpec8.yml
@@ -11,30 +11,60 @@ jobs:
     runs-on: ubuntu-latest
     strategy:
       matrix:
-        axis-os: ["10.12.153"]
+        include:
+          - arch: aarch64
+            chip: artpec8
+            axis-os: 10.12.153
     env:
       EXREPO: acap3-examples
       EXNAME: tensorflow-to-larod-artpec8
-      arch: aarch64
-      chip: artpec8
     steps:
       - uses: actions/checkout@v3
       - uses: docker/setup-buildx-action@v2
 
-      - name: Build ${{ env.EXNAME }} application
+      - name: Build ${{ env.example }} application
         env:
-          env_name: ${{ env.EXREPO }}-${{ env.EXNAME }}-env
-          imagetag_env: ${{ env.EXREPO }}_${{ env.EXNAME }}_environment:${{ env.arch }}
-          imagetag: ${{ env.EXREPO }}_${{ env.EXNAME }}${{ env.arch }}
+          example: ${{ env.EXNAME }}
+          imagetag: ${{ env.EXREPO }}_${{ env.EXNAME }}:1.0
         run: |
           docker image rm -f $imagetag
-          docker image rm -f $imagetag_env
-          docker rm -f $env_name
           cd $EXNAME
-          ./build_env.sh $imagetag_env
-          docker run -v /var/run/docker.sock:/var/run/docker.sock --network host --name $env_name $imagetag_env /bin/bash ./build_acap.sh $imagetag
-          docker cp $env_name:/env/build ./build
-          docker stop $env_name
-          docker rm -f $env_name
-          cd ..
+          docker build --no-cache --tag $imagetag . --build-arg TRAIN_EPOCHS=1 --build-arg TUNE_EPOCHS=1
+
+      - name: Check if model file exists and its size
+        env:
+          imagetag: ${{ env.EXREPO }}_${{ env.EXNAME }}:1.0
+          buildpath: /env/training/models
+          modeldir: model
+          modelname: converted_model.tflite
+        run: |
+          found_error=no
+          [ -d $modeldir ] && rm -rf $modeldir
+          mkdir -p ./$modeldir
+          docker cp $(docker create $imagetag):$buildpath/$modelname ./$modeldir
+          if [ -f $modeldir/$modelname ]; then
+            echo "Model file exists"
+            # Check the file size
+            filesize=$(stat --printf="%s" $modeldir/$modelname)
+            minsize=$((1*1024*1024)) # 1MB
+            maxsize=$((10*1024*1024*1024)) # 10GB
+            if [ $filesize -ge $minsize ] && [ $filesize -le $maxsize ]; then
+                echo "Model file size ($filesize bytes) is within the expected range"
+            else
+                echo "Model file size ($filesize bytes) is out of the expected range"
+                found_error=yes
+            fi
+          else
+            echo "Model file does not exist, build directory contains"
+            ls -la $modeldir
+            found_error=yes
+          fi
+
+          # Cleanup
+          [ -d $modeldir ] && rm -rf $modeldir
           docker image rm -f $imagetag
+
+          [ "$found_error" = no ] || {
+            echo "Error found during tests"
+            exit 1
+          }
